name: "Release Manager: sync changelog with PR"

on:
  push:
    branches:
      - nayami
    paths:
      - 'DIFFERENCE.md'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  edit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # headが$GITHUB_REF_NAME, baseがmasterかつopenのPRを1つ取得
      - name: Get PR
        run: |
          echo "pr_number=$(gh pr list --limit 1 --search "head:$GITHUB_REF_NAME base:master is:open" --json number  --jq '.[] | .number')" >> $GITHUB_OUTPUT
        id: get_pr
      - name: Get target version
        if: steps.get_pr.outputs.pr_number != ''
        uses: yamisskey-dev/release-manager-actions/.github/actions/get-target-version@v2-yamisskey
        id: v
      # CHANGELOG.mdの内容を取得
      - name: Get changelog
        if: steps.get_pr.outputs.pr_number != ''
        uses: yamisskey-dev/release-manager-actions/.github/actions/get-changelog@v2-yamisskey
        with:
          version: ${{ steps.v.outputs.target_version }}
        id: changelog
      # PRのnotesを更新
      - name: Update PR
        if: steps.get_pr.outputs.pr_number != ''
        run: |
          gh pr edit "$PR_NUMBER" --body "$CHANGELOG"
        env:
          PR_NUMBER: ${{ steps.get_pr.outputs.pr_number }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
