name: "Release Manager [Dispatch]"

on:
  workflow_dispatch:
    inputs:
      merge:
        type: boolean
        description: 'MERGE RELEASE BRANCH TO MAIN'
        default: false

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      is_nayami: ${{ steps.check.outputs.is_nayami }}
    steps:
      - name: Check if branch is nayami
        id: check
        run: |
          if [ "${{ github.ref_name }}" = "nayami" ]; then
            echo "is_nayami=true" >> $GITHUB_OUTPUT
          else
            echo "is_nayami=false" >> $GITHUB_OUTPUT
            echo "::error::This workflow only supports nayami branch. Current branch: ${{ github.ref_name }}"
            exit 1
          fi

  create-release-pr:
    needs: check-branch
    if: ${{ needs.check-branch.outputs.is_nayami == 'true' }}
    uses: yamisskey-dev/release-manager-actions/.github/workflows/create-target.yml@v2-yamisskey
    with:
      difference_path: 'DIFFERENCE.md'
      package_jsons_to_rewrite: '["package.json"]'
      indent: 2
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

  merge-release-pr:
    runs-on: ubuntu-latest
    needs: check-branch
    if: ${{ needs.check-branch.outputs.is_nayami == 'true' && inputs.merge == true }}
    steps:
      - uses: actions/checkout@v4
      - name: Get and merge PR
        run: |
          pr_number=$(gh pr list --limit 1 --search "head:$GITHUB_REF_NAME base:master is:open" --json number --jq '.[] | .number')
          if [ -n "$pr_number" ]; then
            gh pr merge $pr_number --merge
          else
            echo "No open PR found to merge"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
